version: "3.9"

services:
  server:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "9000:80"
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: gestiondeventepharmacy
      DB_USERNAME: postgres
      DB_PASSWORD: yacine2005

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: gestiondeventepharmacy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yacine2005
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: laravel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
